version: '3.9'

volumes:
  pgdata: {}
  opensearch: {}

networks:
  freshmark-net:

services:
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: 'true'
    networks:
      - freshmark-net
    depends_on:
      - opensearch
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    volumes:
      - opensearch:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    environment:
    - node.name=opensearch
    - discovery.type=single-node
    - plugins.security.disabled=true
    - OPENSEARCH_INITIAL_ADMIN_PASSWORD=[p^zUI780~Oe
    networks:
      - freshmark-net
  freshmark-db:
    container_name: postgre
    image: 'postgres:latest'
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: admin
      
    
